ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
= SpringJavaConfig

Podczas pracy z tym repozytorium poruszysz tematy:

. Podstawy konfiguracji adnotacjami - `@Autowired`, `@Qualifier`, `@Required`.
. Wstrzykiwanie przez pole, setter oraz konstruktor.
. Wstrzykiwanie kolekcji.
. Tworzenie specjalistycznych ziaren - `Controller`, `Service` i `Repository`

=== Jak pracować z tym repozytorium?
W bieżącym pakiecie znajduje się plik o nazwie **Spring - konfiguracja przez adnotacje.pptx**, który przedstawia
prezentację wprowadzającą do tematyki konfiguracji adnotacjami. Zapoznaj się z nią w pierwszej kolejności.

Następnie przejdź do pakietu 'przykład_konfiguracji_adnotacjami'. Znajdziesz tam gotową implementację aplikacji
webowej.

Kroki, które powinieneś wykonać (zadania koderskie, jak i odnośniki do dokumentacji)
znajdziesz w dokumentacji pakietu (patrz plik package-info.java).

=== Co gdy już wszystko przerobiłem?
Na sam koniec zostaje zadanko koderskie. W katalogu `resources` znajdziesz
gotowy diagram klas. Zaimplementuj aplikację w zgodzie z tym diagramem.

CAUTION: Jeśli zdecydujesz się na implementowanie tego zadania w tym repozytorium (co jest zalecane),
to pamiętaj o tym, że w tym projekcie jest już jeden działający kontroler. Tworzenie
nowego może wymagać modyfikacji już istniejącego kontrolera, z powodów do których
(mam nadzieję) dojdziesz na własną rękę.