= Warsztaty Spring - wstrzykiwanie zależności i cykl życia ziaren.

Pakiet zawierające przykłady oraz zadania na temat wstrzykiwania zależności oraz cyklu życia ziaren w Springu.
Spring na potrzeby warsztatów został skonfigurowany poprzez adnotacje.
Zadania znajdują się na gałęzi: `master`

Ich rozwiązania zostały umieszczone na gałęzi: `rozwiązania`

Podjęta w warsztatach tematyka to:

. Wstrzykiwanie zależności poprzez:
  .. kontruktory
  .. metody set
  .. pola
. Określenie wstrzykiwanej zależności poprzez adnotację `@Qualifier`.
. Użycie metody `afterPropertiesSet()` i `destroy()` oraz adnotacji `@PostConstruct` i `@PreDestroy`.
. `InitializingBean`, `DisposableBean`.
. `BeanPostProcessor`.
. Problem zależności cyklicznych w tworzeniu ziaren.
. Tworzenie ziaren świadomych kontekstu poprzez wykorzystanie interfejsu `Aware`.


== Wstrzykiwanie zależności

Technika realizująca D z SOLIDu, czyli odwracanie zależności (ang. Dependency Inversion). W wykonaniu Springa oddajemy kontrolę nad tworzeniem naszych obiektów Springowi - on tworzy instancje i _wstrzykuje je_ tam, gdzie są potrzebne.

Zależności dla danego ziarna są wyrażone jako właściwości, argumenty konstruktora bądź metody fabrycznej. Są dostarczane ziarnu w momencie jego tworzenia.
Każda właściwość, każdy argument, są wartościami lub odniesieniami do innego ziarna.

== Zakres życia ziarna

. *Singleton* - domyślny zakres, jeden egzemplarz na kontekst.
. *Prototyp* - wiele egzemplarzy
. Sieciowe: sesyjny, żądania, globalnej sesji.
. *Dopasowany* - gdy żaden z powyższych nie pasuje.

=== Singleton

.Jedna instancja jest wstrzykiwana wszystkim trzem potrzebującym ziarnom
[source, xml]
----
<beans xmlns="...">
    <bean id="accountDao" class="..." />
    <!-- ciach -->
    <bean id="Something" class="...">
        <property name="accountDao" ref="accountDao"/>
    </bean>
    <bean id="SomeOtherThing" class="...">
        <property name="accountDao" ref="accountDao"/>
    </bean>
    <bean id="SomethingThird" class="...">
        <property name="accountDao" ref="accountDao"/>
    </bean>
</beans>
----

=== Prototyp

.Każdy kolaborator potrzebujący instancją accountDao dostaje nową, świeżutką instancję, stworzoną przez kontener specjalnie na ten cel
[source, xml]
----
<beans xmlns="...">
    <bean id="accountDao" class="..." scope="prototype"/>
    <!-- ciach -->
    <bean id="Something" class="...">
        <property name="accountDao" ref="accountDao"/>
    </bean>
    <bean id="SomeOtherThing" class="...">
        <property name="accountDao" ref="accountDao"/>
    </bean>
    <bean id="SomethingThird" class="...">
        <property name="accountDao" ref="accountDao"/>
    </bean>
</beans>
----

=== Tworzenie kontekstu

TIP: Jeśli diagram się nie wyświetla, zainstaluj Asciidoctor-diagram lub (do przeglądu w IDE) pobierz asciidoctor-diagram-j.

[ditaa, diagTworzeniaKontekstu, png]
....
                   +-----------------+
                   | klasy aplikacji |
                   +-----------------+
                       |
                       |
                       |
                       v
 +--------+   +--------+----+    /----------------\
 | Konfig |---+ kontekst    +--> | Gotowy do akcji|
 |     {d}|   +-------------+    |       system   |
 +---+----+                      |                |
                                 \----------------/
....

=== Kontener

NOTE: tu będzie ilustracja. Kiedyś. ;-P open-source - możesz ją dodać Ty!

=== Instancjonowanie ziaren

. przez konstruktor, refleksją
. statyczne metody fabryczne
. instancyjne metody fabryczne

== Cykl życia

[syntrax, diagCykluŻyciaZiarna, png]
....
stack(
line('Instancjonowanie', 'Populacja własności  '),
line('BeanNameAware.setBeanName()', 'BeanFactoryAware.setBeanFactory()'),
line('ApplicationContextAware.setApplicationContext()'),
line('Preinicjacja BeanPostProcessor', 'Inicjacja afterPropertiesSet()'),
line('Własna metoda init() ', 'Postinicjacja BeanPostProcessor'),
line('Ziarno gotowe!', '...', 'Kontener się zamyka '),
line('destroy()', 'Własna metoda destroy()'),
)
# puste spacje na końcu konieczne z racji na znaki diakrytyczne
....

=== Pytania

. Na jakie sposoby można wstrzykiwać zależności w Springu?
. Jakiej techniki używa Spring by tworzyć instancje ziaren?
. Jaki jest domyślny zakres ziarna?
. Czy Springowe ziarna singletonowe są bezpieczne wielowątkowo?
. Czy używając zakresu SCOPE na ziarnie, możemy mieć więcej niż jedną instancję danej klasy?